server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true
    username: root
    password: badziewie1
  jpa:
    hibernate:
      ddl-auto: update